### ISSUE TITLE
ios_attachments not working

### ISSUE THREAD

**Issue by vaibhavn1** [OneSignal/OneSignal-Cordova-SDK#100]
Hi team,

I tried upgrading my App to use Rich Notifications using ios_attachments. But it is isnt working. 

I tried with jpg and mp3 file , none of them worked. It works pre ios 10 notifications. 

Note: I was using the latest SDK.

**Comment by zergiocosta** [comment]
Have you tried to send it through one signals dashboard?

I'm getting the same problem here... If I send any media within the notification through the onesignal dashboard, it works perfectly fine! But as far as I try to configure the json with the "ios_attachments" param, nothing happens! =(

Does anyone have any solution for this?

**Comment by vaibhavn1** [comment]
I tried from both .. Once the notification was delivered but there was no media file 

Get Outlook for iOS




On Tue, Oct 11, 2016 at 8:42 PM +0530, "Sergio Costa" <notifications@github.com> wrote:












Have you tried to send it through one signals dashboard?



I'm getting the same problem here... If I send any media within the notification through the onesignal dashboard, it works perfectly fine! But as far as I try to configure the json with the "ios_attachments" param, nothing happens! =(



Does anyone have any solution for this?

**Comment by jkasten2** [comment]
@vaibhavn1 Please verify all of the 3 requires for iOS 10 media attachments.
https://documentation.onesignal.com/docs/troubleshooting-ios#section-ios-notifications-with-action-buttons-or-media-set-not-displaying 

This also requires our 2.0 SDK, run the following to make sure you are up to date.
`cordova plugin list`

@zergiocosta Can you verify you are sending the JSON correct for `ios_attachments`? It needs to be a JSON Object. Example:
`{"id1": "https://domain.com/image.jpg"}`
https://documentation.onesignal.com/reference#create-notification

**Comment by zergiocosta** [comment]
@jkasten2 I've tried like this:
`"ios_attachments": {
		"id": "URL_TO_A_JPG_FILE"
	}`

**Comment by jlillop** [comment]
I have another problem, the new notification (with image) always replace the last notification on my iPhone. Why? the parameter "collapse_id" is not included...

**Comment by zergiocosta** [comment]
@jlillop I think you should pass different params, like

First notification:
`"ios_attachments": { "id": "URL_TO_A_JPG_FILE" }`

Next notification:
`"ios_attachments": { "id1": "URL_TO_A_JPG_FILE" }`

Third notification:
`"ios_attachments": { "id2": "URL_TO_A_JPG_FILE" }`

... ... ...

Have you tried that?

**Comment by jkasten2** [comment]
@jlillop This issue has been fixed in our native iOS 2.2.0 SDK, We will be including this fix in our next SDK update.

**Comment by jkasten2** [comment]
@zergiocosta @jlillop We just released version 2.0.7 which includes our iOS native 2.2.1 SDK which fixes this issue.

**Comment by 01abhishekjain** [comment]
@jkasten2 currently on onesignal-cordova-plugin 2.0.11 but still facing this issue i.e. notifications with "ios_attachments" key are not received AT ALL if the app is force closed (swiped away from recents section). Although they are being received fine on Android.

The [troubleshooting page](https://documentation.onesignal.com/docs/troubleshooting-ios#section-notification-display-issues) tells me that this issue has been solved completely for native iOS SDK 2.4.0. When will the cordova SDK be release that includes this iOS native 2.4.0 SDK ??

**Comment by jkasten2** [comment]
@01abhishekjain I am shooting for a release with this included around the beginning for June.

**Comment by 01abhishekjain** [comment]
@jkasten2 how about reopening the issue till that time, because the v2.0.7 hasn't really solved this. Thanks.

**Comment by jkasten2** [comment]
@01abhishekjain The original issue of them not working at all has been fixed in that version. The limitation is noted in issue #126.  I have updated its title to better reflect the issue.

**Comment by 01abhishekjain** [comment]
@jkasten2 I would love for this to be implemented soon, as would everyone. Can we expect a release sometime soon?

**Comment by kwakueshun** [comment]
I am trying to send rich notifications with an attachment which is an image. when I use any url, it works but the url from my firebase storage does not work even when I add ?filetype=file.jpg to the url

**Comment by jkasten2** [comment]
@kwakueshun Can you share the URL so we can look into reproducing the issue?

**Comment by episquare** [comment]
Anybody in here please give me an example how to show image when notification arrive? i mean example code, currently im using ios 11... i already include json about image url and id as ios attacment, but how to received the image url... please example code guys.. thanks

**Comment by jkasten2** [comment]
@episquare There is some extra setup you must do for the OneSignal SDK to receive and show a [rich media attachment](https://documentation.onesignal.com/docs/rich-media#section-rich-notifications) on a notification. Make sure you have followed all the steps under "5. iOS - Part 2"
https://documentation.onesignal.com/docs/cordova-sdk-setup#section-5-ios-part-2-recommend-
