### ISSUE TITLE
handleNotificationOpened not triggered after app is killed on iOS or ended by OS

### ISSUE THREAD

**Issue by Inoverse** [OneSignal/OneSignal-Cordova-SDK#121]
Following situation:
I register handleNotificationOpened with OneSignal registration after user logged into app.

After I moved to the home screen, I recieve a notification with additional data. If I click on this notification the app is opened and handles the onNotificationOpened event. So, everything is fine.

Following not working situation:
I kill my app through the task switcher or the iOS is ending the app. If I get a new notification (same as the working above), I click on it, app opens but handleNotificationOpened is not triggered.

Any suggestions?

**Comment by joaotocilo** [comment]
It's happening to me too.

**Comment by Inoverse** [comment]
Yep. Me too. iOS 10.1.1

**Comment by Neto-Pavanini** [comment]
+ 1

**Comment by Cestos** [comment]
Me too

**Comment by rafaelyokota** [comment]
+1

**Comment by rafalopesb** [comment]
+1

**Comment by gdeglin** [comment]
Thanks for the reports. We're looking into this.

**Comment by Bausen** [comment]
+1

**Comment by zaidattar** [comment]
same thing on Android 6.01(Samsung Note 7 edge)

**Comment by jkasten2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cordova - Fix open event on code start of app.](https://trello.com/c/ssLcZ7Fl/7-cordova-fix-open-event-on-code-start-of-app)

**Comment by Inoverse** [comment]
@jkasten2 your link redirects to a private trello board. What's the content? 🙄

**Comment by Bausen** [comment]
@jkasten2 ?

**Comment by jkasten2** [comment]
Fixed in commit 5e6afa1a37fadf227c58ab46369b8dd7685aa907 and included in the 2.0.9 release.

**Comment by Inoverse** [comment]
Issue seems not to be fixed.

Still the same behaviour. If I hard kill my app and clicking on a received notification the handleOpened event is not fired.

Any special things to keep in mind for a working solution?

**Comment by jkasten2** [comment]
@Inoverse I wasn't able to reproduce an issue on the 2.0.9 or 2.0.10 OneSignal SDK on iOS 10 or 9. Make sure you are calling from the following from the first page that loads with your app.

```javascript
document.addEventListener('deviceready', function () {
 var notificationOpenedCallback = function(jsonData) {
    alert(JSON.stringify(jsonData));
    console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
  };

  window.plugins.OneSignal
    .startInit("YOUR_APPID")
    .handleNotificationOpened(notificationOpenedCallback)
    .endInit();
}, false);
```

Make sure your app isn't navigating to another page right away after loading otherwise the event might be lost.

Could you try reproducing the issue in a new project and link it to this issue?

**Comment by Inoverse** [comment]
Got it. Haven't added it to the deviceReady-Event. My init was in in the login page. Works now! Thanks. I'm closing the issue.

**Comment by Neto-Pavanini** [comment]
@jkasten2 It has the same behavior as before. If I kill the app it doesn´t receive the notification with the buttons anymore, even when I used the example above. In Android it Works perfectly though.

In my environment I´m using:
cordova 6.4.0 and Ionic
IOS 10.1.1
OneSignal 2.0.10

**Comment by Inoverse** [comment]
My problem was not to add the init function in document ready event. Have you tried this?

**Comment by Neto-Pavanini** [comment]
@Inoverse 
Yes, no successes =/

**Comment by jkasten2** [comment]
@Neto-Pavanini Buttons and media attachments have some extra requirements on iOS. See our [Notifications with action buttons or iOS 10 media not displaying](https://documentation.onesignal.com/docs/troubleshooting-ios#section-notifications-with-action-buttons-or-ios-10-media-not-displaying) troubleshooting guide.

**Comment by marcoiacobelli** [comment]
Hi guys,
I have the same issue.

I don't understand why "handleNotificationOpened" is not trigger when app is closed.
I try to add handleNotificationOpened in onDeviceReady function but the event is not fired.
Any ideas about? 

p.s. I try to add init function too in onDeviceReady function but nothing changed.

Any suggestions are welcome.

Tnx

m.

**Comment by nkete** [comment]
Same issue here. When starting a closed app by clicking on a notification, launch options are lost and not passed to the JS plugin. 

This happens on iOS 11.0.3 and 10.2.1, with `onesignal-cordova-plugin 2.2.1`. 
Using [ionic native plugin](https://ionicframework.com/docs/native/onesignal/) or `window.plugins.OneSignal` is the same, also placing the `oneSignal.init()` inside or out of `platform.ready()` has no effect.

**Comment by jkasten2** [comment]
@nkete For iOS 11, you must be using `onesignal-cordova-plugin` version 2.2.2 for the open callback to fire.

The open callback should fire on iOS 10 however on 2.2.1. Can you make sure you are initializing OneSignal only once and on the first page that starts with your app?

**Comment by nkete** [comment]
Thanks @jkasten2, `2.2.2` does the trick on both devices
