### ISSUE TITLE
v2.0.9 auto prompts for ios device notification registartion at the start of app even if kOSSettingsAutoPrompt is set to false

### ISSUE THREAD

**Issue by vivekpd15** [OneSignal/OneSignal-Cordova-SDK#127]
Hi,

I am facing this error since updation to v2.0.9 of the plugin from v2.0.8. I have not changed any js code and had just updated the plugin after which this problem started to occur. Facing this in iOS9 as well as iOS10.

The piece of code that I am using for initialization is as follows:

var iosSettings = {};
 iosSettings["kOSSettingsKeyAutoPrompt"] = false;
 iosSettings["kOSSettingsKeyInAppLaunchURL"] = false;

 window.plugins.OneSignal.startInit("YOUR_APPID","YOUR_GOOGLE_PROJECT_NUMBER_IF_ANDROID").handleNotificationOpened(function (jsonData) {
      console.log(JSON.stringify(jsonData));
}).iOSSettings(iosSettings).endInit();

**Comment by jkasten2** [comment]
@vivekpd15 Thanks for the report. We just fixed this in commit f242daf7f0961aa3060a9723708bd79b161c58b3 and created a 2.0.10 release with this fix.

**Comment by erdimeola** [comment]
This issue still seems to happen, eventhough I've set kOSSettingsKeyAutoPrompt to false, as soon as I've start my init function, it prompts for push permission on iOS.

`window.plugins.OneSignal
.startInit("ONESIGNAL ID")
.iOSSettings({kOSSettingsKeyAutoPrompt:false, kOSSettingsKeyInAppLaunchURL: false})
.inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.InAppAlert)
.handleNotificationReceived(function(jsonData) {
    ////NOTIFICATION RECEIVED HANDLING
})
.handleNotificationOpened(function(jsonData) {
    //NOTIFICATION CLICK HANDLING
})
.endInit();`

cordova version 7.0.1
onesignal-cordova-plugin 2.2.1
cordova ios 4.4.0
tested on iPhone 6 iOS 11

**Comment by winniestreet** [comment]
I am having the exact same problem
