### ISSUE TITLE
FATAL: OneSignal AppId format is invalid

### ISSUE THREAD

**Issue by baztypetrucci** [OneSignal/OneSignal-Cordova-SDK#312]
```
FATAL: OneSignal AppId format is invalid.
Example: 'b2f7f966-d8cc-11e4-bed1-df8f05be55ba'
```
I'm using 
`onesignal-cordova-plugin 2.2.5 "OneSignal Push Notifications"`

When I make `ionic cordova build ios --release` everything goes well, but when I run it in Xcode, the logs says the mentioned error.

If I check my markup:

`this.OneSignal.startInit('d75fe80c-38c9-496e-8792-fe2eff96f7f3')`

Everything is correctly set.

**Comment by Nightsd01** [comment]
This issue has been addressed in a recent update and should now be resolved. Please let me know if you encounter any further issues.

**Comment by ntambwadev** [comment]
Hi, I installed the cordova-sdk today and I am still experiencing this issue. I'm using:
`<plugin name="onesignal-cordova-plugin" spec="^2.3.1" />`
which i support installs: 
`pod 'OneSignal', '2.7.1'`

**Comment by adefokun** [comment]
I have this issue too.

**Comment by Nightsd01** [comment]
This issue should not be resolved in the new update (2.3.2) @adefokun @ntambwadev 

Please let me know if you have any further issues with this and I'd be happy to help, thank you.

**Comment by ntambwadev** [comment]
Thank you! @Nightsd01 I think you forgot to update package.json to 2.3.2

**Comment by adefokun** [comment]
@Nightsd01 but I see 2.8.1 is the latest release.

**Comment by harryt2** [comment]
I'm getting one that says Fatal Error Onesignal AppId Never Set! Also can't add 2.3.2, it keeps adding 2.3.1

**Comment by jkasten2** [comment]
Sorry for the confusion, the 2.3.2 update is now published to npm.
https://www.npmjs.com/package/onesignal-cordova-plugin

**Comment by adefokun** [comment]
It has worked now. Thanks.

**Comment by harryt2** [comment]
Fixed here too, thank you.
