### ISSUE TITLE
Conflict with cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by doonfrs** [OneSignal/OneSignal-Cordova-SDK#503]
**Description:**

I can not build with cordova-google-maps for android (at least)

**Environment**
1. What version of the Cordova SDK are you using?
9.0.0 (cordova-lib@9.0.1)

2. Provide a list of your project dependencies
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-build-increment 2.0.1 "Cordova Build Increment Tool"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.0 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"

**Steps to Reproduce Issue:**
1. create ionic 3 project
2. cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps
3. ionic cordova plugin add onesignal-cordova-plugin
4. add <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="******" /> to config.xml
5. ionic cordova build android
BUILD FAILED in 4s
28 actionable tasks: 4 executed, 24 up-to-date
/root/projects/busvibe/mobile-user/platforms/android/gradlew: Command failed with exit code 1 Error output:
/root/projects/busvibe/mobile-user/platforms/android/app/src/main/AndroidManifest.xml:27:66-112 Error:
        Attribute meta-data#com.google.android.geo.API_KEY@value at AndroidManifest.xml:27:66-112 requires a placeholder substitution but no value for <GOOGLE_MAPS_ANDROID_API_KEY> is provided.
/root/projects/busvibe/mobile-user/platforms/android/app/src/main/AndroidManifest.xml Error:
        Validation failed, exiting

I think that the plugin reset the variable value for google maps, because build go successful with maps plugin alone, or with onesignal plugin again.
* I filed the same issue on googlemaps plugin because I do not know the one responsible for the error.

Thank you!

**Comment by jlrpuma** [comment]
how can we handle that?, i have the same problem but i need to use the two plugins(One Signal and Google Maps), any solutions at the moment?

**Comment by zedlen** [comment]
I have the same problem and like @jlrpuma  I also need bot plugins, is there any solution?

**Comment by jlrpuma** [comment]
@zedlen i decide to use the following configuration
<plugin name="cordova-plugin-googlemaps" spec="^2.5.3">
<plugin name="onesignal-cordova-plugin" spec="^2.4.6" />

in my case im using Ionic, so i delete the android platform, and remove both plugins, after that reinstall google maps plugin (2.5.3), do a build for android, when the build is ready you can install onesignal plugin (2.4.6).

PD:. i use this config on google maps plugin
<plugin name="cordova-plugin-googlemaps" spec="^2.5.3">
        <variable name="API_KEY_FOR_ANDROID" value="***" />
        <variable name="API_KEY_FOR_IOS" value="***" />
        <variable name="PLAY_SERVICES_VERSION" value="11.8.0" />
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="24.1.0" />
        <variable name="LOCATION_WHEN_IN_USE_DESCRIPTION" value="This app wants to get your location while this app runs only." />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="This app wants to get your location always, even this app runs in background." />
    </plugin>

**Comment by battika** [comment]
+1

**Comment by doonfrs** [comment]
> @zedlen i decide to use the following configuration
> 
> in my case im using Ionic, so i delete the android platform, and remove both plugins, after that reinstall google maps plugin (2.5.3), do a build for android, when the build is ready you can install onesignal plugin (2.4.6).
> 
> PD:. i use this config on google maps plugin
> 
> ```
> <plugin name="cordova-plugin-googlemaps" spec="^2.5.3">
>         <variable name="API_KEY_FOR_ANDROID" value="***" />
>         <variable name="API_KEY_FOR_IOS" value="***" />
>         <variable name="PLAY_SERVICES_VERSION" value="11.8.0" />
>         <variable name="ANDROID_SUPPORT_V4_VERSION" value="24.1.0" />
>         <variable name="LOCATION_WHEN_IN_USE_DESCRIPTION" value="This app wants to get your location while this app runs only." />
>         <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="This app wants to get your location always, even this app runs in background." />
>     </plugin>
> ```

Unfortunately, we need latest google maps version.
currently, one of plugins resetting the other one variables, I think it is onesignal.

**Comment by fareshan** [comment]
+1

**Comment by wf9a5m75** [comment]
cordova-plugin-googlemaps v2.6.1 resolves this problem.

**Comment by battika** [comment]
Thanks Masashi, I confirm that cordova-plugin-googlemaps v2.6.2 is now picking up the key properly at compile time.

**Comment by rgomezp** [comment]
Sounds like this is now resolved. Thanks @battika

**Comment by kapilSoni101** [comment]
@rgomezp: sir why you have closed above issue this issue is still here please open again.
@doonfrs and @jlrpuma sir i am not any onesignal plugin i am using only firebase plugin and i am also using cordova plugin google maps 2.6.2 version.
I have remove platform as well reinstall plugin but nothing worked me.tell me aby another way to fix this error?

**Comment by rgomezp** [comment]
@kapilSoni101 ,
Since you are not using the onesignal plugin, the issue seems to be with something else. I encourage you to open an issue with the other plugin vendor.

**Comment by kapilSoni101** [comment]
@rgomezp: ok sir thanks for your response but sir i am not understand which plugin is conflict.tell me one thing sir which cordova-plugin-googlemaps version are you used.
I have tried 2.4.4 and 2.6.2 if i used 2.4.4 i have another multiple errors what i do sir
