### ISSUE TITLE
OneSignal Cordova SDK - No custom sound / custom sound not working correctly / res/raw folder directory

### ISSUE THREAD

**Issue by elmbrent** [OneSignal/OneSignal-Cordova-SDK#510]
I have added the file via config.xml to my res/raw directory and it is not playing my custom audio files, just the normal beep.

Added line to config.xml  <resource-file src="test.mp3" target="res/raw/test.mp3" />

See image
https://ibb.co/KVBg0ds

**Environment**
CORDOVA 9.0.0
Phonegap 7.1.0
Android  6.4.0

**Steps to Reproduce Issue:**
  1. Added file to www and root
  2. Tried adding test.mp3 to Message and test
  3. Tried different phonegap and android version

**Comment by Benjyclay** [comment]
I've got the same issue - Did anyone solve this?

**Comment by rgomezp** [comment]
@elmbrent , @Benjyclay Can you please check in the apk if the resource is actually being added? Also, please check in the notification info that the sound is not set to Default.

**Comment by elmbrent** [comment]
@rgomezp If you look at the screenshot you can see the file being added to the android directory automatically, I did check the response and it was meant to be playing the file without the extension.

**Comment by rgomezp** [comment]
@elmbrent I know that the file is supposed to be added from looking at the screenshot, but you have to check the APK itself to see if it is actually where it is supposed to be (look in the directory itself)

**Comment by elmbrent** [comment]
@rgomezp  can you advise how I can look inside of the APK file, I'm guessing I need to decompile it?

**Comment by rgomezp** [comment]
@elmbrent Ok that's good. But it looks like you're not putting it in the correct directory. 

**Solution**: Make sure it is in `<project-root>/platforms/android/res/raw/`

If you take a look at our [docs](https://documentation.onesignal.com/docs/customize-notification-sounds#section-android-and-derivatives-like-amazon-), you will see that the dir is different for different platforms

**Comment by elmbrent** [comment]
@rgomezp  It is in the directory, after it is complied into an APK the whole directory structure is different that, what you are saying is the directory structure before compiling

**Comment by rgomezp** [comment]
@elmbrent ,
After sending a notification, can you check the Realtime Message Data page for the following:
<img width="1002" alt="Screen Shot 2019-05-22 at 1 56 00 PM" src="https://user-images.githubusercontent.com/11739227/58208547-c9dc2880-7c99-11e9-8dec-dda6e6dea235.png">

**Comment by elmbrent** [comment]
https://ibb.co/26jqwqD 

Yes it seems to be set, just the normal phone beep sounds appears though

**Comment by rgomezp** [comment]
How about on iOS? Is it working there?

**Comment by elmbrent** [comment]
We have not tried yet, we are doing an android release soon so we would like to get this fixed

**Comment by AcidTr** [comment]
I have almost the same issue. I run the command to generate the apk, but the sound isn't copied to the correct directory.
I'd already tried to use diffrent config.xml commands to copy the sound file, but nothing works.
![image](https://user-images.githubusercontent.com/35748259/58436068-f331f580-8099-11e9-8f74-074bc536eb35.png)

Here's the apk screenshot of the folder res/raw
![image](https://user-images.githubusercontent.com/35748259/58436133-2e342900-809a-11e9-9f85-502224622e52.png)

**Comment by rgomezp** [comment]
@elmbrent , could you please test on iOS? This will give me a better idea of what is happening.

@AcidTr , it sounds like your issue is different as it isn't being even copied to the correct directory. Just curious, what is the empty.wav file?

**Comment by AcidTr** [comment]
@rgomezp
I don’t know what is this empty.wav file. It just appeared there. One time I tried to build the apk and there was the correct file, but it had 0 bytes. And the empty.wav was there too

**Comment by rgomezp** [comment]
Try doing a recursive search through the entire project to see if it's being copied at all @acidtr

**Comment by AcidTr** [comment]
@rgomezp nothing was found

**Comment by rgomezp** [comment]
If nothing was found, I don't think it has to do with the OneSignal SDK. For some reason the file isn't being copied. Try searching for reasons this could be happening

**Comment by AcidTr** [comment]
@rgomezp as I remember the OneSignal's docs said to just put the file inside the folder <project-root>/platforms/android/res/raw/. I Already put it there and the file still wasn't copied.

**Comment by rgomezp** [comment]
What about the `src`? Are you sure the source is in the correct directory? Take a look at the official [Cordova docs](https://cordova.apache.org/docs/en/5.0.0/plugin_ref/spec.html#resource-file-and-header-file-elements) regarding this

**Comment by AcidTr** [comment]
Yes, it is!

**Comment by rgomezp** [comment]
@AcidTr , 
I would open an issue with Apache Cordova since this is a build issue unrelated to OneSignal

**Comment by AcidTr** [comment]
@rgomezp , I have just solved it. I just changed the path of the target from "res/raw/phonering.wav" to "app/src/main/res/raw/phonering.wav"

**Comment by elmbrent** [comment]
AcidTr can you post a link of your config.xml, I think that would help me out loads!

**Comment by AcidTr** [comment]
@elmbrent I'm using cordova 8.1.2. Maybe there's some diffrence between versions about this tag <resource-file>
![image](https://user-images.githubusercontent.com/35748259/59359230-5b244500-8d04-11e9-813e-e3b2ca4e42d9.png)

**Comment by elmbrent** [comment]
I will give this a try thankyou

**Comment by AcidTr** [comment]
"cordova-android": "7.1.4"

**Comment by rgomezp** [comment]
Thanks for following up

**Comment by project30003** [comment]
This is not working with android 8.0.0 and above

**Comment by blinks32** [comment]
worked for me

**Comment by sergiol29** [comment]
Hi, I've similar issue. When I send a notification with default sound or custom sound the android devices show notification but only vibrate and don't play any sound.

At devices iOS I have not issues, the devices show notification and play sound correctly.

First issue was I've issue that I run the command to generate the apk, the sound wasn't copied to the correct directory and I solved with this line in config.xml:
![Captura de pantalla 2019-09-30 a las 14 05 58](https://user-images.githubusercontent.com/15367305/65877258-78e8e900-e38b-11e9-9c95-e9db3f9fc694.png)

As second step, I configured a category on oneSignal as you can see in the next picture:
<img width="700" alt="Captura de pantalla 2019-09-30 a las 14 09 09" src="https://user-images.githubusercontent.com/15367305/65877412-ebf25f80-e38b-11e9-8d0e-dc64a1f8cb38.png">

And last step, I generate a notification and the options I select "urgent" category:
<img width="686" alt="Captura de pantalla 2019-09-30 a las 14 11 17" src="https://user-images.githubusercontent.com/15367305/65877528-38d63600-e38c-11e9-91ad-a985768b993c.png">

Also, I tested with default sound at the category:
<img width="703" alt="Captura de pantalla 2019-09-30 a las 14 15 21" src="https://user-images.githubusercontent.com/15367305/65877804-d9c4f100-e38c-11e9-98af-db95faf0ea05.png">

But my devices show the notification and don't play any sound and only vibrate.
I tested in several devices and nothing devices play sound.

To init oneSignal in my project, I developed the next function:
![Captura de pantalla 2019-09-30 a las 14 17 44](https://user-images.githubusercontent.com/15367305/65878121-928b3000-e38d-11e9-85da-83ea492b6dc6.png)

**NOTE:** I don`t have the devices on silent when receiving the push notifications.

Could you help me?
Thanks.

**Comment by rgomezp** [comment]
Take a look at our [docs](https://documentation.onesignal.com/docs/customize-notification-sounds#section-android-and-derivatives-like-amazon-). It looks like you may not have it in the right path

**Comment by efebello** [comment]
@sergiol29 Did you found a solution? I'm facing exactly the same problem (Android). 
Worse, in my case, the custom sound does not sound (it only vibrates) when I update the APK. 
If I do a clean installation of the APK it sounds correct.

Sound files have the correct file extension
Sound files are encoded in a supported format
Sound files are in the correct location
Sound files are not too long
Sound files are in the APK when I look/decompile

Thanks

**Comment by spinninghamster** [comment]
Does anyone have a solution? We checked and all the paths are correct and the same app receives notification sounds on Android 8 but not on Android 9.

**Comment by sergiol29** [comment]
I fixed up the issue, I installed different versions the plugin OneSignal-Cordova-SDK (https://github.com/OneSignal/OneSignal-Cordova-SDK/releases) until the issue was fixep up (version 2.6.0) because the last version I do not worked for me

**Comment by spinninghamster** [comment]
> Take a look at our [docs](https://documentation.onesignal.com/docs/customize-notification-sounds#section-android-and-derivatives-like-amazon-). It looks like you may not have it in the right path

This issue shouldn't be closed. It's still happening to a lot of people and clearly a real problem. We wanted to use OneSignal but this problem was too much for us, so we switched back to plain Firebase.

We made sure all the paths are correct, the files are in correct formats, not too long, ensured that after building they are there, etc.

The issue for us was that on some Android versions it worked and on others it didn't. When we switched back to plain Firebase it worked fine on every version.

There's clearly a problem here..

**Comment by Waterloo** [comment]
Does anyone have a solution?

**Comment by rgomezp** [comment]
Howdy,
@rcpinheiro says this solved the issue. Try:
```
In my case I just had to change the destination folder:
<resource-file src="/res/notificacao/mybell.mp3" target="app/src/main/res/raw/mybell.mp3" />

It seems the official docs are wrong.
```

**Comment by ahliit** [comment]
Is this issue still open? The solution above is not working for me.
