### ISSUE TITLE
Macbook M1 : App won't build on simulator but works fine on device

### ISSUE THREAD

**Issue by jay34fr** [OneSignal/OneSignal-Cordova-SDK#682]
**Description:**

Hi all,

I try to build my app on a MacBook Pro with Silicon M1 chip. 
After several headhaches on installing homebrew and cocoapods with Rosetta, the app is now building on the device and everything is fine.

But it won't build on the simulator.

I have the common error : 
/Users/xxx/xx/x/x/platforms/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), **building for iOS Simulator, but linking in object file built for iOS**, file /Users/xxx/xx/x/x/platforms/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I saw many posts about this issue, eg : 
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios?

* I tried to put "arm68" on the "excluded architectures" but same error.
* I tried to Set "Build Active Architecture Only (ONLY_ACTIVE_ARCH)" to Yes ,  but same error.
* I didn't have any "VALID_ARCH" settings in "User-defined"

When I remove the Onesignal plugin, my app is builded on simulator without any errors.

Do you have the same issue ? Any solution ?

Thx in advance for your help, I am really stuck.

Jay

**Environment**

* Cordova 9.0.0
* Cordova iOS 5.1.1 (still working well on my MacBook Pro no M1), Is Cordova 6.x.x mandatory ?
* onesignal-cordova-plugin 2.11.2
* Cocoapods 1.10.0
* Xcode 12.2

**Comment by emawby** [comment]
@jay34fr Hello my guess is that the fat framework that we use in the pod has its iOS simulator build target using the x86_64 (since that is what intel based macs would need), but the arm mac uses arm64 for its simulator. Unfortunately this will require an iOS Native fix where we might need a separate framework version that is just for apple silicon macs. I apologize for the inconvenience

**Comment by jay34fr** [comment]
Thx @emawby for your answer. 😉

So you think there is no solution for the moment ?

It will be really difficult for devs because we need the simulator in order to create screenshots for the app review.

But... I only need to remove the OneSignal plugin in order to have the app builded in the simulator for those screenshots, so I have my "solution"...

Thx again and I really hope that there will be a solution asap.

😉

**Comment by rgomezp** [comment]
Howdy @jay34fr ,
Unfortunately there is no solution the moment for any of the wrapper SDKs. This has been resolved at the native level however. We will need to investigate next steps on making it available via our other SDKs.

In the meantime, you can continue working around the issue via Rosetta.

If anyone wants a challenge and would like contribute to the SDK, any help would be appreciated in investigating next steps. 

A good starting point is investigating whether pointing Cocoapods at the [XCFramework](https://documentation.onesignal.com/docs/using-onesignals-xcframework-for-mac-catalyst) instead of the normal OneSignal framework works.

Cheers

**Comment by jay34fr** [comment]
Hi @rgomezp , thx for your answer.
Unfortunately, I am not enough skilled to help you but I will send you good vibes for it 👍🏻

Cheers !

**Comment by halpz** [comment]
this is still an issue on the latest version of your SDK, every other framework has been updated to work with M1 except yours!

**Comment by alancook** [comment]
Same problem can we get a new version

**Comment by halpz** [comment]
Timescale?

**Comment by jay34fr** [comment]
Did you update to version 2.11.3 ?
https://github.com/OneSignal/OneSignal-Cordova-SDK/releases

Seems it's will be ok with : iOS Native SDK Update 2.16.1 : "The OneSignal XCFramework now supports arm64 iOS simulators for Apple Silicon Macs. #836"

**Comment by alancook** [comment]
#Pharma Quiz Apps
target 'Pharma Quiz' do
	platform :ios, '14.3'
	project 'Apps/Apps.xcodeproj'
	app_shared_pods_ios
	pod 'OneSignal'
end

target 'OneSignalNotificationServiceExtension' do
	platform :ios, '14.3'
	project 'Apps/Apps.xcodeproj'
	pod 'OneSignal'
end

ld: in /Users/alanc/Code/SharedApps/Apps/CodeFabPH/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/alanc/Code/SharedApps/Apps/CodeFabPH/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Can I not use the pod ‘OneSignal’ this compiles fine on my intel Mac mini


Alan Cook
Senior Programmer
CodeFab
alanc@mac.com
www.codefab.com

**Comment by danielehrhardt** [comment]
Same Problem here. Is there a new Version already released?

**Comment by rgomezp** [comment]
@danielehrhardt ,
Howdy,
The Cordova major release is just around the corner.

Thanks for your patience.

**Comment by sdbarrington** [comment]
Any update on this?

**Comment by rgomezp** [comment]
Howdy,
We released the major release beta version: https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/3.0.0-beta1

Please give that a shot.

Cheers

**Comment by alancook** [comment]
When do expect to have a working Cocopod?

Alan Cook
Senior Programmer
CodeFab
***@***.***
www.codefab.com

**Comment by RubSR** [comment]
Same problem with 

> Howdy,
> We released the major release beta version: https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/3.0.0-beta1
> 
> Please give that a shot.
> 
> Cheers

The problems  still exists

**Comment by danielehrhardt** [comment]
```
ld: in /Users/danielehrhardt/projects//ios/App/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS,
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by geun** [comment]
still problems

**Comment by jkasten2** [comment]
@geun You will need to use onesignal-cordova-plugin 3.0.0 or newer which has support for the simulator on macOS systems with an Arm chip (M1).
See the upgrade guide on doing so:
https://documentation.onesignal.com/docs/step-by-step-cordova-2x-to-300-upgrade-guide

The change that was made to support this was done in this commit:
https://github.com/OneSignal/OneSignal-Cordova-SDK/commit/644bb47fbbd3176411a2a34b86072d2ff70c46d6

**Comment by emawby** [comment]
In addition to using version 3.0.0+ make sure you are using the OneSignalXCFramework pod instead of the OneSignal pod for your NotificationServiceExtension. XCFrameworks are the new universal binary format that supports both M1 and Intel architectures for all platforms.

**Comment by luizping** [comment]
Trying to install and continue getting an error.

Cordova Packages:

    cli: 11.0.0
        common: 4.0.2
        create: 4.0.0
        lib: 11.0.0
            common: 4.0.2
            fetch: 3.0.1
            serve: 4.0.0

Project Installed Platforms:
 ios: 6.2.0

Project Plugins:
onesignal-cordova-plugin: 3.0.2

Environment:

OS: macOS Monterey 12.2.1 (21D62) (darwin 21.3.0) arm64
    Node: v17.6.0
    npm: 8.5.3



when try to install onesignal plugin, get this error:

Installing "onesignal-cordova-plugin" for ios
Running command: pod install --verbose
objc[2133]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x202c1f678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1045282c8). One of the two will be used. Which one is undefined.

objc[2133]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x202c1f6c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104528318). One of the two will be used. Which one is undefined.

Searching for inspections failed: undefined method `map' for nil:NilClass

Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 1 Error output:
objc[2133]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x202c1f678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1045282c8). One of the two will be used. Which one is undefined.
objc[2133]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x202c1f6c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104528318). One of the two will be used. Which one is undefined.
Searching for inspections failed: undefined method `map' for nil:NilClass
    at ChildProcess.whenDone (/Users/luizdias/jobs/comune/castellabate/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:688:12)
pod: Command failed with exit code 1 Error output:
objc[2133]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x202c1f678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1045282c8). One of the two will be used. Which one is undefined.
objc[2133]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x202c1f6c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104528318). One of the two will be used. Which one is undefined.
Searching for inspections failed: undefined method `map' for nil:NilClass


Maybe because it's trying to run: pod install instead of: arch -x86_64 pod install
